### ISSUE TITLE
Quick start guide has incorrect link to repo

### ISSUE THREAD

**Issue by danyork** [rdbinteractive/wpdd#1]
Hi - this WP DryDock is very cool! Thank you for building it.

FYI, on the "Quick Start" page on WPDryDock - https://docs.wpdrydock.com/quick-start - under step 2 where you say to clone the repo, you are pointing to:

https://github.com/rdbinteractive/rdbiwp

which gives a 404. I suspect you mean to point to https://github.com/rdbinteractive/wpdd

**Comment by rdbinteractive** [comment]
I'm glad you find it cool! Link fixed Thank you for pointing it out.
